---
title: "Data_Wrangling"
author: "Madie Tong"
date: "2024-04-25"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyverse)
library(tidycensus)
library(tmap)
library("readxl")
library(ggmap)
knitr::opts_chunk$set(echo = TRUE)
```

Addresses of Properties Qualified for 421a Tax Exemption
[link](https://www.nyc.gov/site/finance/property/benefits-421a.page)
```{r}
properties_421a_22_23 <- read_xlsx("/home/mtong1/data-science/urban_gentrification/data/raw_data/421a_2023_brooklyn.xlsx")

clean_prop <-
  properties_421a_22_23 %>%
  mutate(Address = str_to_title(Address)) %>%                                 # Converting addresses into better, parse-able format 
  mutate(full_addy = paste(Address, ZIP_CODE, sep = ", Brooklyn, NY ")) %>%   # Completing each address and adding zip code
  filter(YEAR_BUILT > 0) %>%                                                  # Filtering rows without proper years
  distinct(YEAR_BUILT, full_addy, .keep_all = T) %>%                          # taking out rows with duplicate pairs of year and addresses
  arrange(desc(YEAR_BUILT))
```
Number of Units Qualified for Tax Exemptions per Borough
[link](https://furmancenter.org/files/publications/The_Role_of_421-a_Final.pdf)
*This data frame was manually created using values taken from the above article in Table 2 on page 10.*
```{r}
residential_developments = data.frame(
  tax_type = c("421a", "421a","421a","421a","421a","420c", "420c", "420c", "420c", "420c", "other", "other", "other", "other", "other", "none reported", "none reported", "none reported", "none reported", "none reported"),
  borough = c("bronx", "brooklyn", "manhattan", "queens", "staten_island","bronx", "brooklyn", "manhattan", "queens", "staten_island","bronx", "brooklyn", "manhattan", "queens", "staten_island","bronx", "brooklyn", "manhattan", "queens", "staten_island"),
  units = c(9216, 49654, 33791, 23573, 808, 15617, 6811, 3575, 3401, 292, 771, 2169, 1665, 2572, 140, 693, 7840, 7033, 2254, 30)
) 
# %>%
  # write.csv("/home/mtong1/data-science/urban_gentrification/data/residential_developments.csv", row.names=FALSE)
```
Total Low Income Units 
[link](https://furmancenter.org/neighborhoods/view/brooklyn)
```{r}
borough_low_income_units <- read_csv("/home/mtong1/data-science/urban_gentrification/data/raw_data/focus_databrooklyn.csv", show_col_types = FALSE)
spec(borough_low_income_units)


borough_low_income_units <- 
  borough_low_income_units %>%
# separating borough and borough number to write out boroughs in name 
  separate(col=Geography, into = c("borough", "borough num"), sep=" ") %>%
  mutate(borough = recode(borough, BX = 'Bronx', MN = "Manhattan", QN = "Queens", SI = "Staten Island", BK = "Brooklyn")) %>%
# separating number of units per column from the percentage 
  separate(col=market_rate_units, into = c("market_rate_units", "market_rate_units_percentage"), sep=" ") %>%
  separate(col=mi_mod_units, into = c("mi_mod_units", "mi_mod_units_percentage"), sep=" ") %>%
  separate(col=low_income_units, into = c("low_income_units", "low_income_units_percentage"), sep=" ") %>%
  separate(col=unknown_units, into = c("unknown_units", "unknown_units_percentage"), sep=" ") %>%
# taking out commas in unit numbers for parsing, converting to doubles for math operations 
  mutate(low_income_units = as.double(gsub(",","",low_income_units)),
         mi_mod_units = as.double(gsub(",","", mi_mod_units)),
         market_rate_units = as.double(gsub(",","", market_rate_units)),
         unknown_units = as.double(gsub(",","", unknown_units)))


summed_borough_units <- 
  borough_low_income_units %>%
# summing over units per borough for each category of unit
  group_by(borough)%>% 
  mutate(total_low_income =sum(low_income_units),
         total_mi_mod = sum(mi_mod_units),
         total_market = sum(market_rate_units),
         total_unknown = sum(unknown_units)) %>%
# removing non-useful columns
  select(borough, total_mi_mod, total_low_income, total_market, total_unknown) %>%
# removing duplicate rows 
  distinct(borough, total_mi_mod, total_low_income, total_market, total_unknown, .keep_all = T) %>%
  pivot_longer(!borough, names_to = "income_type", values_to = "total")


residential_developments <- 
  residential_developments %>%
  mutate(borough = gsub("_", " ", borough)) %>% # removing underscore from staten island values
  mutate(borough = str_to_title(borough)) %>% # converting first letters to uppercase for ease of joining datasets
  filter(tax_type == "421a")


# joining two datasets
units_low_income_421a <- merge(summed_borough_units, residential_developments, by=c("borough")) %>%
  rename(units_421a = units) %>%
  select(!tax_type) %>%
  filter(income_type == "total_low_income") %>%
  select(!income_type) %>%
  pivot_longer(!borough, names_to = "unit_type", values_to = "value") %>%
  mutate(unit_type = recode(unit_type, total="Total Low Income Units", units_421a = "Total 421a Exempt Units"))
```
Median Gross Rent 
[link](https://furmancenter.org/neighborhoods/view/brooklyn)
```{r}
median_rent <- read_csv("/home/mtong1/data-science/urban_gentrification/data/raw_data/median_rent_data.csv")

borough_median_rent <-
  median_rent %>%
  filter(Level == "Boro") %>%
  select(!Geography) %>%
  select(!Level) %>%
  pivot_longer(!Name, names_to = "year", values_to = "value") %>%
# removing $ and , from price value for parsing
  mutate(value = gsub(",","", value)) %>%
  mutate(value = gsub("\\$", "", value))


brooklyn_median_rent <-
  median_rent %>%
# separating borough num and borough to select only brooklyn numbers
  separate(col=Geography, into = c("borough", "borough_num"), sep=" ") %>%
  filter(!is.na(borough_num), borough == "BK") %>%
  select(!borough) %>%
  select(!Level) %>%
  select(!borough_num) %>%
  pivot_longer(!Name, names_to = "year", values_to = "rent") %>%
  mutate(rent=gsub("\\$", "", rent)) %>%
  mutate(rent=as.double(gsub(",", "", rent)))
```
Linear Model of Median Rent Increase from 2006-2021 vs 421a Qualified Units in CD's of Brooklyn 
[link](https://app.coredata.nyc/?mlb=false&ntii=shd_421a_units&ntr=Community%20District&mz=14&vtl=https%3A%2F%2Fthefurmancenter.carto.com%2Fu%2Fnyufc%2Fapi%2Fv2%2Fviz%2F98d1f16e-95fd-4e52-a2b1-b7abaf634828%2Fviz.json&mln=true&mlp=true&mlat=40.718&nty=2022&mb=roadmap&pf=%7B%22subsidies%22%3Atrue%7D&md=table&mlv=false&mlng=-73.996&btl=Borough&atp=neighborhoods)
```{r}
# making a dataset with just borough CD number and CD name 
num_CD_names <- 
  median_rent %>% 
  select(Geography, Name) %>%
  separate(col=Geography, into=c("borough", "borough_num"), sep=" ") %>%
  filter(!is.na(borough_num), borough == "BK") %>%
  select(!borough) %>%
  mutate(borough_num = as.double(borough_num))

# number of 421a qualified units per CD of Brooklyn 
CD_421a <- read_csv("/home/mtong1/data-science/urban_gentrification/data/raw_data/communitydistrict-421-ataxexemptionunits.csv") %>%
# filtering for Brooklyn 
  separate(col="Community District", into = c("Borough", "borough_num"), sep=" ") %>%
  filter(Borough=="BK") %>%
  mutate(borough_num = as.double(borough_num)) %>%
# joining together Community District names since it's not included in the original dataset 
  left_join(num_CD_names, by=c("borough_num")) %>%
  select(-c(short_name, long_name, Borough)) %>%
  rename(unit_nums = "2022")

diff_median_rent <- 
  brooklyn_median_rent %>%
  filter(year == c(2006, 2021)) %>%
  pivot_wider(names_from = "year", values_from = "rent") %>%
# calculating median rent increase by taking difference of starting year to ending year 
  mutate(diff = `2021` - `2006`) %>%
  select(-c(`2021`, `2006`)) %>%
# adding numbers of 421a qualified units by Community District name 
  left_join(CD_421a, by="Name")
```
