---
title: "project_vis"
author: "Madie Tong"
date: "2024-04-15"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyverse)
library(tidycensus)
library(tmap)
library("readxl")
library(ggmap)
knitr::opts_chunk$set(echo = TRUE)
```

## Prev Stuff 

```{r, echo=FALSE}
# kings_2010 <- read_csv("uscensus_kingscounty_income/kingscounty_income_2010.csv")
# kings_2013 <- read_csv("uscensus_kingscounty_income/kingscounty_income_2013.csv")
# kings_2016 <- read_csv("uscensus_kingscounty_income/kingscounty_income_2016.csv")
# kings_2019 <- read_csv("uscensus_kingscounty_income/kingscounty_income_2019.csv")
# kings_2021 <- read_csv("uscensus_kingscounty_income/kingscounty_income_2021.csv")
```

## Census Data for median income and race percentages in Kings County by Year
```{r, echo=FALSE}

# 2022
income_race_2022 <- tidycensus::get_acs(state = "NY",
                                county = "Kings",
                                geography="tract",
                                variables = c("B19013_001", "B01003_001E"), # median, total pop
                                year=2022,
                                geometry=TRUE) %>%
 select(-moe) %>%
  pivot_wider(names_from=variable, values_from=estimate) %>%
  mutate(median_household_income_2022 = 1*`B19013_001`) %>%
  # rename(median_household_income=`B19013_001`) %>%
  select(-`B19013_001`) %>%
  filter(!is.na(median_household_income_2022)) %>%
  mutate(state_code=str_sub(GEOID,1,2), county_code=str_sub(GEOID,3,5)) %>%
  left_join(select(fips_codes, c(state_code, county_code, county))) %>%
  mutate(county = str_remove(county, " County"))

income_race_2016 <- tidycensus::get_acs(state = "NY",
                                county = "Kings",
                                geography="tract",
                                variables = c("B19013_001", "B01003_001E"), # median, total pop
                                year=2016,
                                geometry=TRUE) %>%
  select(-moe) %>%
  pivot_wider(names_from=variable, values_from=estimate) %>%
  mutate(median_household_income_2016 = 1*`B19013_001`) %>%
  # rename(median_household_income=`B19013_001`) %>%
  select(-`B19013_001`) %>%
  filter(!is.na(median_household_income_2016)) %>%
  mutate(state_code=str_sub(GEOID,1,2), county_code=str_sub(GEOID,3,5)) %>%
  left_join(select(fips_codes, c(state_code, county_code, county))) %>%
  mutate(county = str_remove(county, " County"))

income_race_2010 <- tidycensus::get_acs(state = "NY",
                                county = "Kings",
                                geography="tract",
                                variables = c("B19013_001", "B01003_001E"), # median, total pop
                                year=2010,
                                geometry=TRUE) %>%
  select(-moe) %>%
  pivot_wider(names_from=variable, values_from=estimate) %>%
  mutate(median_household_income_2010 = 1*`B19013_001`) %>%
  # rename(median_household_income=`B19013_001`) %>%
  select(-`B19013_001`) %>%
  filter(!is.na(median_household_income_2010)) %>%
  mutate(state_code=str_sub(GEOID,1,2), county_code=str_sub(GEOID,3,5)) %>%
  left_join(select(fips_codes, c(state_code, county_code, county))) %>%
  mutate(county = str_remove(county, " County"))

income_race_all <- st_join(income_race_2022, income_race_2016, left=FALSE)

income_race_2000 <- tidycensus::get_decennial(state = "NY",
                                county = "Kings",
                                geography="tract",
                                variables = c("B19013_001", "B01003_001E"), # median, total pop
                                year=2000,
                                geometry=TRUE) %>%
  select(-moe) %>%
  pivot_wider(names_from=variable, values_from=estimate) %>%
  mutate(median_household_income_2000 = 1*`B19013_001`) %>%
  # rename(median_household_income=`B19013_001`) %>%
  select(-`B19013_001`) %>%
  filter(!is.na(median_household_income_2000)) %>%
  mutate(state_code=str_sub(GEOID,1,2), county_code=str_sub(GEOID,3,5)) %>%
  left_join(select(fips_codes, c(state_code, county_code, county))) %>%
  mutate(county = str_remove(county, " County"))

# 2016
# income_race_2016 <- tidycensus::get_acs(state = "NY",
#                                 county = "Kings",
#                                 geography="tract",
#                                 variables = c("B19013_001", "B01003_001E", "B02001_002E", "B02001_003E", "B02001_004E", "B02001_005E"), # median, total pop, white,afr,native, asian
#                                 year=2016,
#                                 geometry=TRUE) %>%
#  select(-moe) %>%
#   pivot_wider(names_from=variable, values_from=estimate) %>%
#   mutate(percent_white_alone=100*`B02001_002`/`B01003_001`, 
#          percent_african_american_alone=100*`B02001_003`/`B01003_001`,
#          percent_native_alone = 100*`B02001_004`/`B01003_001`,
#          percent_asian_alone = 100*`B02001_005`/`B01003_001`)%>%
#   rename(median_household_income=`B19013_001`) %>%
#   select(-c(`B02001_002`, `B02001_003`, `B02001_004`, `B02001_005`, `B01003_001`)) %>%
#   filter(!is.na(median_household_income)) %>%
#   mutate(state_code=str_sub(GEOID,1,2), county_code=str_sub(GEOID,3,5)) %>%
#   left_join(select(fips_codes, c(state_code, county_code, county))) %>%
#   mutate(county = str_remove(county, " County"))
```

## Creating Figures for each Year 
```{r, echo=FALSE}
fig1_2022 <- tm_shape(income_race_2022) + 
  tm_polygons(col = "median_household_income",
              n = 10,
              border.alpha=.3,
              palette = "-Blues",
              title = "2022 US Census") + 
  tm_layout(title = "Median Household Income \nby Census Tract",
            frame = FALSE,
            legend.outside = TRUE)

# fig2_2022 <- 
```
```{r}
tmap_arrange(fig1_2022,fig2_2022,fig3_2022,fig4_2022, fig5_2022,nrow=2)
tmap_arrange(fig1_2016,fig2_2016,fig3_2016,fig4_2016, fig5_2016,nrow=2)
tmap_arrange(fig1_2010,fig2_2010,fig3_2010,fig4_2010, fig5_2010,nrow=2)
```


```{r}
# https://www.nyc.gov/site/finance/property/benefits-421a.page

properties_421a_22_23 <- read_xlsx("/home/mtong1/data-science/urban_gentrification/data/raw_data/421a_2023_brooklyn.xlsx")
# proper addys 
clean_prop <-
  properties_421a_22_23 %>%
  mutate(Address = str_to_title(Address)) %>%
  mutate(full_addy = paste(Address, ZIP_CODE, sep = ", Brooklyn, NY ")) %>%
  filter(YEAR_BUILT > 0) %>%
  distinct(YEAR_BUILT, full_addy, .keep_all = T) %>%
  arrange(desc(YEAR_BUILT))

prop_addies <-
  clean_prop %>%
  select(NEIGHBORHOOD, full_addy) %>%
  write.csv("/home/mtong1/personal/421a_brooklyn_addresses.csv", row.names=FALSE)

clean_prop_bars <- 
  clean_prop %>%
  select(BOROUGH, YEAR_BUILT)

total <- aggregate(clean_prop_bars, by=list(clean_prop_bars$BOROUGH, clean_prop_bars$YEAR_BUILT), FUN = length) %>%
  select(Group.1, Group.2, BOROUGH) %>%
  rename(total=BOROUGH, BOROUGH = Group.1, year = Group.2)

ggplot(total, aes(x=year, y=total)) + 
  geom_col()


prop_2021_2017 <- 
  clean_prop %>%
  filter(YEAR_BUILT > 2016) %>%
  arrange(desc(YEAR_BUILT))

prop_2016_2011 <- 
  clean_prop %>%
  filter(YEAR_BUILT > 2011, YEAR_BUILT < 2017)
```
```{r}
# new_columns = geo(
#   address = prop_2021_2017$full_addy, method = "osm",
#   lat = latitude, long = longitude)


# address = "11 Wall St, NY, NY"
# geocode(properties_421a_22_23$Address)
# address1 = "2143 BENSON AVENUE 11214"
# 
# osm_s1 <- geo(
#   address = address1, method = "osm",
#   lat = latitude, long = longitude)

residential_developments = data.frame(
  tax_type = c("421a", "421a","421a","421a","421a","420c", "420c", "420c", "420c", "420c", "other", "other", "other", "other", "other", "none reported", "none reported", "none reported", "none reported", "none reported"),
  borough = c("bronx", "brooklyn", "manhattan", "queens", "staten_island","bronx", "brooklyn", "manhattan", "queens", "staten_island","bronx", "brooklyn", "manhattan", "queens", "staten_island","bronx", "brooklyn", "manhattan", "queens", "staten_island"),
  units = c(9216, 49654, 33791, 23573, 808, 15617, 6811, 3575, 3401, 292, 771, 2169, 1665, 2572, 140, 693, 7840, 7033, 2254, 30)
)

# source: https://furmancenter.org/files/publications/The_Role_of_421-a_Final.pdf
ggplot(residential_developments, aes(x=tax_type, y = units, fill=borough))+
  geom_col(position="dodge") +
  labs(x="Tax Exemption Type",y= "Number of Units per Borough", title="Units per Borough Qualified for Property Tax Exemption Completed (2010-2020)")
```

```{r}
# https://data.cityofnewyork.us/City-Government/DOF-Summary-of-Neighborhood-Sales-by-Neighborhood-/5ebm-myj7/about_data
neighborhood_sales <- read_csv("/home/mtong1/Downloads/DOF__Summary_of_Neighborhood_Sales_by_Neighborhood_Citywide_by_Borough_20240424.csv")
unique(neighborhood_sales$YEAR)

clean_sales <- 
  neighborhood_sales %>%
  filter(BOROUGH == "BROOKLYN" | BOROUGH == 3, !is.na(NEIGHBORHOOD), `TYPE OF HOME` == "03 THREE FAMILY HOMES") 
unique(clean_sales$YEAR)

colnames(clean_sales)

ggplot(clean_sales, aes(x=`YEAR`, y=`MEDIAN SALE PRICE`, color=`NEIGHBORHOOD`)) +
  geom_point()+
  geom_line() +
  theme(legend.title = element_text(size = 3), 
        legend.text = element_text(size = 3))
  facet_wrap(~`NEIGHBORHOOD`, scales="free")+
  labs(x="Year", y = "Median Sales Price ($)", title="Median Property Sales Price by Brooklyn Neighborhood (2010-2022)")

# ggplot(clean_sales, aes(x=`YEAR`, y=`MEDIAN SALE PRICE`, color = `NEIGHBORHOOD`, group=`NEIGHBORHOOD`))+
#   geom_point()+
#   geom_line()+
#   labs(x="Year", y = "Median Sales Price")

```
library(dplyr)
```{r}
# https://furmancenter.org/neighborhoods/view/brooklyn 
# of low income units per borough
borough_low_income_units <- read_csv("/home/mtong1/data-science/urban_gentrification/data/raw_data/focus_databrooklyn.csv", show_col_types = FALSE)
spec(borough_low_income_units)

# cleaning 
borough_low_income_units <- 
  borough_low_income_units %>%
  separate(col=Geography, into = c("borough", "borough num"), sep=" ") %>%
  mutate(borough = recode(borough, BX = 'Bronx', MN = "Manhattan", QN = "Queens", SI = "Staten Island", BK = "Brooklyn")) %>%
  separate(col=market_rate_units, into = c("market_rate_units", "market_rate_units_percentage"), sep=" ") %>%
  separate(col=mi_mod_units, into = c("mi_mod_units", "mi_mod_units_percentage"), sep=" ") %>%
  separate(col=low_income_units, into = c("low_income_units", "low_income_units_percentage"), sep=" ") %>%
  separate(col=unknown_units, into = c("unknown_units", "unknown_units_percentage"), sep=" ") %>%
  mutate(low_income_units = as.double(gsub(",","",low_income_units)),
         mi_mod_units = as.double(gsub(",","", mi_mod_units)),
         market_rate_units = as.double(gsub(",","", market_rate_units)),
         unknown_units = as.double(gsub(",","", unknown_units)))
  
# Total Low Income
ggplot(borough_low_income_units, aes(x=borough, y = low_income_units)) + 
  geom_col()+
  labs(x="Borough", y="Number of Low Income Units", title="Total Low Income Units Built by Borough (2010-2020)")

# summing over total low income units for each borough
summed_borough_units <- 
  borough_low_income_units %>%
  group_by(borough)%>% 
  mutate(total_low_income =sum(low_income_units),
         total_mi_mod = sum(mi_mod_units),
         total_market = sum(market_rate_units),
         total_unknown = sum(unknown_units)) %>%
  select(borough, total_mi_mod, total_low_income, total_market, total_unknown) %>%
  distinct(borough, total_mi_mod, total_low_income, total_market, total_unknown, .keep_all = T) %>%
  pivot_longer(!borough, names_to = "income_type", values_to = "total")

# Total Units All
ggplot(summed_borough_units, aes(x=borough, y = total, fill=income_type)) + 
  geom_bar(stat='identity', position='dodge')+
  labs(x="Borough", y="Number of Units Built", title="Total Units Built by Borough (2010-2020)")

# library(stringr)
residential_developments <- 
  residential_developments %>%
  mutate(borough = gsub("_", " ", borough)) %>%
  mutate(borough = str_to_title(borough)) %>%
  filter(tax_type == "421a")

units_low_income_421a <- merge(summed_borough_units, residential_developments, by=c("borough")) %>%
  rename(units_421a = units) %>%
  select(!tax_type) %>%
  filter(income_type == "total_low_income") %>%
  select(!income_type) %>%
  pivot_longer(!borough, names_to = "unit_type", values_to = "value") %>%
  mutate(unit_type = recode(unit_type, total="Total Low Income Units", units_421a = "Total 421a Exempt Units"))
  # write.csv("/home/mtong1/data-science/urban_gentrification/data/units_low_income_421a.csv", row.names=FALSE)


ggplot(units_low_income_421a, aes(x=borough,y=value, fill=unit_type)) + 
  geom_bar(stat="identity", position="identity", alpha=.5)+
  labs(x="Borough", y="Number of Units", title="Low Income and 421a Qualified Units per Borough (2010-2021)")
```

```{r}
median_rent <- read_csv("/home/mtong1/data-science/urban_gentrification/data/raw_data/median_rent_data.csv")

# ALL BOROUGHS 
borough_median_rent <-
  median_rent %>%
  filter(Level == "Boro") %>%
  select(!Geography) %>%
  select(!Level) %>%
  pivot_longer(!Name, names_to = "year", values_to = "value") %>%
  mutate(value = gsub(",","", value)) %>%
  mutate(value = gsub("\\$", "", value))
  # write.csv("/home/mtong1/data-science/urban_gentrification/data/borough_median_rent.csv", row.names=FALSE)

ggplot(borough_median_rent, aes(x=year, y=value, color=Name, group=Name))+
  geom_point()+
  geom_line()+
  labs(x="Year", y="Rent ($)", title="Median Gross Rent by Borough (2006-2021)")

# BROOKLYN COMMUNITY 
brooklyn_median_rent <-
  median_rent %>%
  separate(col=Geography, into = c("borough", "borough_num"), sep=" ") %>%
  filter(!is.na(borough_num), borough == "BK") %>%
  select(!borough) %>%
  select(!Level) %>%
  select(!borough_num) %>%
  pivot_longer(!Name, names_to = "year", values_to = "rent") %>%
  mutate(rent=gsub("\\$", "", rent)) %>%
  mutate(rent=as.double(gsub(",", "", rent)))
  # write.csv("/home/mtong1/data-science/urban_gentrification/data/brooklyn_median_rent.csv", row.names=FALSE)

# BROOKLYN MEDIAN GROSS RENT 
ggplot(brooklyn_median_rent, aes(x=year, y=rent, group=Name, color=Name)) +
  geom_point()+
  geom_line()+
  labs(x="Year", y="Median Rent", title="Median Gross Rent by Neighborhood in Brooklyn (2006-2021)", col = "Neighborhood") +
  theme(legend.title = element_text(size = 3), 
               legend.text = element_text(size = 3))

```
```{r}
library(gganimate)
# https://www.nyc.gov/site/planning/planning-level/nyc-population/nyc-population-geographic-relationships.page
tract_geoid_cdta <- read_xlsx("/home/mtong1/Downloads/nyc_2020_census_tract_nta_cdta_relationships.xlsx") %>%
  select(GEOID, CT2020, CDTACode)

tract_shape <- merge(tract_geoid_cdta, income_race_2022, by="GEOID") %>%
  select(-c(`B01003_001`, state_code, county_code))
  
animate_median_rent <- 
  median_rent %>%
  mutate(Geography = gsub(" ", "", Geography)) %>%
  filter(Level == "Community District") %>%
  mutate(is_brooklyn = str_detect(Geography, "BK")) %>%
  filter(is_brooklyn == TRUE) %>%
  separate(col="Geography", into = c("Borough", "borough_num"), sep="BK") %>%
  select(-c(is_brooklyn, Borough)) %>%
  mutate(borough_num = as.double(borough_num))


copy_names <- animate_median_rent$Name
# animate_median_rent <- full_join(animate_median_rent, tract_shape, by=c("Geography"="CDTACode"))

# https://furmancenter.org/files/sotc/SOC2007_IndexofCommunityDistricts_000.pdf
brooklyn_cd_name <- data.frame(
  Name = copy_names,
  CD = c(201,202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218))

brook_shape <-nyc_boundaries(geography="cd",
               filter_by="borough", 
               region=c("Brooklyn"))%>%
  mutate(cd_id = as.double(cd_id))

separate(col="Community District", into = c("Borough", "borough _num"), sep=" ")
# https://data.cityofnewyork.us/City-Government/Community-Districts/yfnk-k7r4
# NEED TO FILTER bY JOIN BROOKLYN LATER 
joined_animate_median_rent <- full_join(animate_median_rent, brooklyn_cd_name, by=c("Name" = "Name") ) %>%
  inner_join(brook_shape, by=c("borough_num"="cd_id")) %>%
  mutate(`2006` = gsub("\\$","", `2006`),
         `2007` = gsub("\\$","", `2007`),
         `2008` = gsub("\\$","", `2008`),
         `2009` = gsub("\\$","", `2009`),
         `2010` = gsub("\\$","", `2010`),
         `2011` = gsub("\\$","", `2011`),
         `2012` = gsub("\\$","", `2012`),
         `2013` = gsub("\\$","", `2013`),
         `2014` = gsub("\\$","", `2014`),
         `2015` = gsub("\\$","", `2015`),
         `2016` = gsub("\\$","", `2016`),
         `2017` = gsub("\\$","", `2017`),
         `2018` = gsub("\\$","", `2018`),
         `2019` = gsub("\\$","", `2019`),
         `2020` = gsub("\\$","", `2020`),
         `2021` = gsub("\\$","", `2021`)
         ) %>%
  mutate(`2006` = gsub("\\,","", `2006`),
         `2007` = gsub("\\,","", `2007`),
         `2008` = gsub("\\,","", `2008`),
         `2009` = gsub("\\,","", `2009`),
         `2010` = gsub("\\,","", `2010`),
         `2011` = gsub("\\,","", `2011`),
         `2012` = gsub("\\,","", `2012`),
         `2013` = gsub("\\,","", `2013`),
         `2014` = gsub("\\,","", `2014`),
         `2015` = gsub("\\,","", `2015`),
         `2016` = gsub("\\,","", `2016`),
         `2017` = gsub("\\,","", `2017`),
         `2018` = gsub("\\,","", `2018`),
         `2019` = gsub("\\,","", `2019`),
         `2020` = gsub("\\,","", `2020`)
         ) %>%
   st_as_sf() %>%
  pivot_longer(cols=starts_with("20"), names_to="year", values_to="median_rent")

  # pivot_longer(cols=c("2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017","2018","2019","2020","2021"),
  #                     names_to = "year", 
  #                     values_to = "median_rent")



```
```{r}
tm_1 <- tm_shape(joined_animate_median_rent) +
  tm_polygons(col = "year",
              n = 10,
              border.alpha=.3,
              palette = "-Blues",
              title = "median gross rent for year 2006") +
  tm_layout(title = "Median Gross Rent by Brooklyn Neighborhood",
            frame = FALSE,
            legend.outside = TRUE)

tmap_animation(tm_1, delay=40)

tm_shape(joined_animate_median_rent) +
  tm_polygons(col = "2007",
              n = 10,
              border.alpha=.3,
              palette = "-Blues",
              title = "median gross rent for year 2006") +
  tm_layout(title = "Median Gross Rent by Brooklyn Neighborhood",
            frame = FALSE,
            legend.outside = TRUE)

tm_shape(income_race_2022) + 
  tm_polygons(col = "median_household_income_2022",
              n = 10,
              border.alpha=.3,
              palette = "-Blues",
              title = "2022 US Census") + 
  tm_layout(title = "Median Household Income \nby Census Tract",
            frame = FALSE,
            legend.outside = TRUE)
```
```{r}
fig1_2016 <- tm_shape(income_race_2016) +
  tm_polygons(col = "median_household_income_2016",
              n = 10,
              border.alpha=.3,
              palette = "-Blues",
              title = "2016 US Census") + 
  tm_layout(title = "Median Household Income \nby Census Tract",
            frame = FALSE,
            legend.outside = TRUE)

num_CD_names <-
  animate_median_rent %>%
  select(borough_num, Name) %>%
  mutate(borough_num = as.double(gsub("BK","", borough_num)))
```
```{r}
remotes::install_github("mfherman/nycgeo")
library(nycgeo)
```
```{r}
# furman center core data 
CD_421a <- read_csv("/home/mtong1/Downloads/communitydistrict-421-ataxexemptionunits.csv") %>%
  separate(col="Community District", into = c("Borough", "borough_num"), sep=" ") %>%
  filter(Borough=="BK") %>%
  mutate(borough_num = as.double(borough_num)) %>%
  left_join(num_CD_names, by=c("borough_num")) %>%
  select(-c(short_name, long_name, Borough)) %>%
  rename(unit_nums = "2022")

# https://data.cityofnewyork.us/City-Government/2020-Census-Tracts-to-2020-NTAs-and-CDTAs-Equivale/hm78-6dwm/about_data CD_
cd_tract_mapping <- read_csv("/home/mtong1/Downloads/2020_Census_Tracts_to_2020_NTAs_and_CDTAs_Equivalency_20240429.csv") %>%
  filter(BoroName == "Brooklyn")%>%
select(CT2020, GEOID, CDTACode) %>%
  mutate(GEOID = as.character(GEOID))

CD_421a_median_income_2022 <- 
  CD_421a %>%
  left_join(income_race_2022, by="GEOID")

income_race_2022_CD <- 
  income_race_2022 %>%
  left_join(cd_tract_mapping, by=c("GEOID" = "GEOID")) %>%
  separate(col = "CDTACode", into = c("Borough", "borough_num"), sep = "BK") %>%
  as.data.frame() %>%
  select(-c(county, county_code, state_code, `B01003_001`, Borough, geometry)) %>%
  mutate(borough_num = as.double(borough_num)) %>%
  group_by(borough_num) %>%
  mutate(median_household_income_2022 = median(median_household_income_2022)) %>%
  select(borough_num, median_household_income_2022) %>%
  unique()%>%
  left_join(CD_421a, by="borough_num") %>%
  
  brook_shape <-nyc_boundaries(geography="cd",
               filter_by="borough", 
               region=c("Brooklyn"))%>%
  mutate(cd_id = as.double(cd_id))
  
model1 <- lm(median_household_income_2022 ~ 1 + unit_nums, data=income_race_2022_CD)  
ggplot(income_race_2022_CD, aes(y=median_household_income_2022, x=unit_nums)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method="lm", se=FALSE)


diff_median_rent <- 
  brooklyn_median_rent %>%
  filter(year == c(2006, 2021)) %>%
  pivot_wider(names_from = "year", values_from = "rent") %>%
  mutate(diff = `2021` - `2006`) %>%
  select(-c(`2021`, `2006`)) %>%
  left_join(CD_421a, by="Name")

ggplot(diff_median_rent, aes(x=unit_nums, y=diff)) +
  geom_point(alpha=0.3) + 
  geom_smooth(method="lm", se=FALSE) + 
  geom_label_repel(label=diff_median_rent$Name, size = 2.5) +
  labs(x="Number of 421a Units", y="Median Rent Increase($)", title="Linear Model of 421a Units Number and Median Rent Increase")

```
```{r}
library(ggrepel)
```
connecting increase in rent in a neighborhood to number of 421a houses 