---
title: "Using Tidyverse for Median Income"
output: html_document
date: "2024-04-16"
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(urltools)
library(jsonlite)
library(DT)
library(tidycensus)
library(viridis)

knitr::opts_chunk$set(tidy = FALSE, message=FALSE, warning=FALSE)
options(htmltools.dir.version = FALSE)
```


```{r}
#Must sign up for a Census key here in order to access the data: https://api.census.gov/data/key_signup.html

# good website for walkthrough: https://walker-data.com/tidycensus/articles/basic-usage.html#searching-for-variables


#census_api_key("be06ef4e79a388a876e38a114656a8ca5d50a55b", install = TRUE, overwrite=TRUE) #insert api key

variables <-load_variables(2017, "acs5", cache = TRUE)


medinc_NY_2020 <- get_acs(geography = "tract", variables = "B19013_001", #median income
                state = "NY", county = "Kings County", geometry = TRUE, year = 2020)
medinc_NY_2009 <- get_acs(geography = "tract", variables = "B19013_001", #median income
                state = "NY", county = "Kings County", geometry = TRUE, year = 2009)

ggplot(medinc_NY_2020, aes(fill = estimate, color = estimate, )) +
  geom_sf() +
  coord_sf(crs = 26914) +
  scale_fill_viridis(option = "magma") +
  scale_color_viridis(option = "magma") +
  ggtitle("Median Income in Brooklyn  2020")

ggplot(medinc_NY_2009, aes(fill = estimate, color = estimate, )) +
  geom_sf() +
  coord_sf(crs = 26914) +
  scale_fill_viridis(option = "magma") +
  scale_color_viridis(option = "magma") +
  ggtitle("Median Income in Brooklyn  2009")

```
