---
title: "ZoningViz"
author: "Merwan Yeditha"
date: "2024-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(choroplethr)
```

```{r}
zap <- read_csv("data/ZAP_ProjectID_Year.csv")
zap <- zap[!is.na(zap$project_name),]
zap <- zap %>% 
  mutate("MIHEXISTS"= if_else(!is.na(mih_flag) | !is.na(mih_option1) | !is.na(mih_option2) | !is.na(mih_deepaffordability), TRUE, FALSE))
```

```{r}
ggplot(data=zap, aes(x=Year, fill=borough)) +
  geom_bar()

ggplot(data=zap, aes(x=Year, fill=borough)) +
  geom_bar(position='fill')
```
```{r}
data_mih = zap[zap$MIHEXISTS,]
ggplot(data=data_mih, aes(x=borough)) +
  geom_bar()
```

```{r}
load("data/Data_NYC_Gentrification_2000_16.RData")
counties <- data.frame("Borough"= c("Bronx", "Brooklyn", "Manhattan", "Queens", "Staten Island"),
                       "Borough_Code"=c("36005", "36047", "36061", "36081", "36085"))
x <- x %>% 
  mutate("Borough_Code"=substring(x$tractid, 0, 5)) %>% 
  inner_join(counties, by="Borough_Code")

x$Borough <- as_factor(x$Borough)
```


```{r}
library(plotly)
library(devtools)
devtools::install_github("lionel-/ggstance")
library(ggstance)
p <- ggplot(data=x, aes(x=NHW0016, y=Borough)) +
  geom_violinh() +
  xlim(c(-2, 30))
p
```

```{r}
x <-x %>% mutate("NHW00PCT"=NHW00/totpop00, "NHW16PCT"=NHW16/totpop16) %>% 
  mutate("NHWPCTDIFF"=NHW16PCT-NHW00PCT) %>% 
  mutate("POSNHWDIFF"= if_else (NHWPCTDIFF > 0, TRUE, FALSE))

lowpct_nhw = x[x$NHW00PCT<.6,]
largepctdiff_nhw = x[order(x$NHWPCTDIFF, decreasing=TRUE)[0:100],]

ggplot(data=largepctdiff_nhw, aes(x=Borough)) +
  geom_bar() +
  labs(y="Change in % Non-Hispanic White", title="100 Census Tracts with Greatest Difference in % Non-Hispanic White Pop. by Borough")
```


```{r}
ggplot(data=x, aes(x=mdfami0016, y=NHWPCTDIFF)) +
  geom_point(alpha=.5, aes(color=Borough)) +
  geom_smooth(method="lm") +
  facet_wrap(~Borough, scales='free')+
  labs(x="% Change Median Family Income 2000-2016", y="Difference in % Non-Hispanic White Pop.")
```

```{r}
brooklyn_data = x[x$Borough=="Brooklyn",]
bronx_data = x[x$Borough=="Bronx",]
queens_data = x[x$Borough=="Queens",]
staten_data = x[x$Borough=="Staten Island",]
manhattan_data = x[x$Borough=="Manhattan",]

mod_brooklyn <- lm(NHWPCTDIFF~1+mdrent0016, data=brooklyn_data)
mod_bronx <- lm(NHWPCTDIFF~1+mdrent0016, data=bronx_data)
mod_queens <- lm(NHWPCTDIFF~1+mdrent0016, data=queens_data)
mod_staten <- lm(NHWPCTDIFF~1+mdrent0016, data=staten_data)
mod_manhattan <- lm(NHWPCTDIFF~1+mdrent0016, data=manhattan_data)
```

```{r}
low_nhw <- quantile(brooklyn_data$NHWPCTDIFF, .025)
high_nhw <- quantile(brooklyn_data$NHWPCTDIFF, .975)
low_mdrent <- quantile(brooklyn_data$mdfami0016, .025)
high_mdrent <- quantile(brooklyn_data$mdfami0016, .975)
brooklyn_data_clean = subset(brooklyn_data,
                             NHWPCTDIFF > low_nhw & NHWPCTDIFF < high_nhw & mdrent0016 > low_mdrent & mdrent0016 < high_mdrent)

x$ntaname = as.factor(x$ntaname)
p2 <- ggplot(data=brooklyn_data_clean, aes(x=mdrent0016, y=NHWPCTDIFF, fill=tractid)) +
  geom_point() +
  geom_smooth(method="lm") +
  labs(title="Brooklyn %change in Med. Rent vs. Change in NHW PCT, middle 95%",y="Difference in % Non-Hispanic White Pop.", x="% Change Median Rent 2000-2016") +
  xlim(c(0, 1.5)) +
  ylim(c(-0.3, 0.3))

ggplotly(p2)

low_nhw <- quantile(bronx_data$NHWPCTDIFF, .025)
high_nhw <- quantile(bronx_data$NHWPCTDIFF, .975)
low_mdrent <- quantile(bronx_data$mdfami0016, .025)
high_mdrent <- quantile(bronx_data$mdfami0016, .975)
bronx_data_clean = subset(bronx_data,
                             NHWPCTDIFF > low_nhw & NHWPCTDIFF < high_nhw & mdrent0016 > low_mdrent & mdrent0016 < high_mdrent)
ggplot(data=bronx_data_clean, aes(x=mdrent0016, y=NHWPCTDIFF)) +
  geom_point() +
  geom_smooth(method="lm") +
  labs(title="Bronx %change in Med. Rent vs. Change in NHW PCT, middle 95%",y="Difference in % Non-Hispanic White Pop.", x="% Change Median Rent 2000-2016") +
  xlim(c(0, 1.5)) +
  ylim(c(-0.3, 0.3))

low_nhw <- quantile(queens_data$NHWPCTDIFF, .025)
high_nhw <- quantile(queens_data$NHWPCTDIFF, .975)
low_mdrent <- quantile(queens_data$mdfami0016, .025)
high_mdrent <- quantile(queens_data$mdfami0016, .975)
queens_data_clean = subset(queens_data,
                             NHWPCTDIFF > low_nhw & NHWPCTDIFF < high_nhw & mdrent0016 > low_mdrent & mdrent0016 < high_mdrent)
ggplot(data=queens_data_clean, aes(x=mdrent0016, y=NHWPCTDIFF)) +
  geom_point() +
  geom_smooth(method="lm") +
  labs(title="Queens %change in Med. Rent vs. Change in NHW PCT, middle 95%",y="Difference in % Non-Hispanic White Pop.", x="% Change Median Rent 2000-2016") +
  xlim(c(0, 1.5)) +
  ylim(c(-0.3, 0.3))

low_nhw <- quantile(manhattan_data$NHWPCTDIFF, .025)
high_nhw <- quantile(manhattan_data$NHWPCTDIFF, .975)
low_mdrent <- quantile(manhattan_data$mdfami0016, .025)
high_mdrent <- quantile(manhattan_data$mdfami0016, .975)
manhattan_data_clean = subset(manhattan_data,
                             NHWPCTDIFF > low_nhw & NHWPCTDIFF < high_nhw & mdrent0016 > low_mdrent & mdrent0016 < high_mdrent)
ggplot(data=manhattan_data_clean, aes(x=mdrent0016, y=NHWPCTDIFF)) +
  geom_point() +
  geom_smooth(method="lm") +
  labs(title="Manhattan %change in Med. Rent vs. Change in NHW PCT, middle 95%",y="Difference in % Non-Hispanic White Pop.", x="% Change Median Rent 2000-2016") +
  xlim(c(0, 1.5)) +
  ylim(c(-0.3, 0.3))

low_nhw <- quantile(staten_data$NHWPCTDIFF, .025)
high_nhw <- quantile(staten_data$NHWPCTDIFF, .975)
low_mdrent <- quantile(staten_data$mdfami0016, .025)
high_mdrent <- quantile(staten_data$mdfami0016, .975)
staten_data_clean = subset(staten_data,
                             NHWPCTDIFF > low_nhw & NHWPCTDIFF < high_nhw & mdrent0016 > low_mdrent & mdrent0016 < high_mdrent)
p1 <- ggplot(data=staten_data_clean, aes(x=mdrent0016, y=NHWPCTDIFF)) +
  geom_point() +
  geom_smooth(method="lm") +
  labs(title="Staten Island %change in Med. Rent vs. Change in NHW PCT, middle 95%", y="Difference in % Non-Hispanic White Pop.", x="% Change Median Rent 2000-2016")+
  xlim(c(0, 1.5)) +
  ylim(c(-0.3, 0.3))

ggplotly(p1)
```

```{r}
brooklyn_data_clean <- brooklyn_data_clean %>% 
  mutate(subdiv = floor(brooklyn_data_clean$tractid/1000))

my_palette <- c("red", "yellow", "green")

bklyn_extra <- ggplot(data=brooklyn_data_clean, aes(x=mdrent0016, y=NHWPCTDIFF, fill=subdiv)) +
  geom_point() +
  geom_smooth(method="lm") +
  labs(title="Brooklyn %change in Med. Rent vs. Change in NHW PCT, middle 95%",y="Difference in % Non-Hispanic White Pop.", x="% Change Median Rent 2000-2016") +
  xlim(c(0, 1.5)) +
  ylim(c(-0.3, 0.3)) +
  scale_fill_gradientn(colors = my_palette)

ggplotly(bklyn_extra)
```

```{r}
mdrentlow <- quantile(x$mdrent0016, .025)
mdrenthigh <- quantile(x$mdrent0016, .975)
x_clean <- subset(x, mdrent0016 > mdrentlow & mdrent0016 < mdrenthigh)
ggplot(data=x, aes(x=Borough, y=mdrent0016)) +
    geom_violin()
ggplot(data=x_clean, aes(x=Borough, y=mdrent0016)) +
    geom_violin() +
  labs(title="Middle 95%", y="% Change in Median Rent 2000-2016")
```

```{r}
housing <- read_csv("data/HousingDB_post2010.csv")
housing <- housing %>% 
  mutate("Borough_Code"=substring(housing$CenTract20, 0, 5)) %>% 
  inner_join(counties, by="Borough_Code")

own_less <- as.factor(str_extract(housing$Ownership, "^[A-Za-z-, ]*"))
housing <- housing %>% 
  mutate("Ownership Reduced"=own_less)
housing$Ownership <- as.factor(housing$Ownership)
housing$Job_Type <- as.factor(housing$Job_Type)
```

```{r}
ggplot(data=housing, aes(x=Borough, fill=Job_Type)) +
  geom_bar() +
  labs(title="New Housing Jobs by Borough")

ggplot(data=housing, aes(x=Borough, fill=`Ownership Reduced`)) +
  geom_bar() +
  labs(title="New Housing Jobs by Borough")

demos = housing[housing$Job_Type=="Demolition",]
ggplot(data=demos, aes(x=Borough, fill=`Ownership Reduced`)) +
  geom_bar() +
  labs(title="Demolition Jobs by Borough")

ggplot(data=demos, aes(x=Borough, fill=`Ownership Reduced`)) +
  geom_bar(position='fill') +
  labs(title="% Ownership of Demolition Jobs by Borough")
```

```{r}
bklyn_housing = housing[housing$Borough=="Brooklyn",]
bronx_housing = housing[housing$Borough=="Bronx",]
manhattan_housing = housing[housing$Borough=="Manhattan",]
queens_housing = housing[housing$Borough=="Queens",]

ggplot(data=housing, aes(x=PermitYear, fill=Borough)) +
  geom_bar() +
  labs(title="Housing Projects by Year", x="Permit Year", y="Count")

ggplot(data=housing, aes(x=PermitYear, fill=Borough)) +
  geom_bar(position='fill') +
  labs(title="% of Housing Projects per Borough by Year", x="Permit Year", y="Count")


ggplot(data=housing, aes(x=PermitYear, fill=Job_Type)) +
  geom_bar() +
  facet_wrap(~Borough, ncol=2) +
  labs(title="Job Type Breakdown per Borough per Year", x="Permit Year", y="Count")

ggplot(data=housing, aes(x=PermitYear, fill=`Ownership Reduced`)) +
  geom_bar() +
  facet_wrap(~Borough, ncol=2) +
  labs(title="Job Type Breakdown per Borough per Year", x="Permit Year", y="Count")

ggplot(data=bklyn_housing, aes(x=PermitYear, fill=`Ownership Reduced`)) +
  geom_bar(position='fill') +
  facet_wrap(~Borough, ncol=2) +
  labs(title="Job Type Breakdown per Borough per Year", x="Permit Year", y="Count")
```

```{r}
bklyn_gov_housing <- bklyn_housing[bklyn_housing$`Ownership Reduced` == "Government, City",]
ggplot(data=bklyn_gov_housing, aes(x=PermitYear, fill=`Ownership`)) +
  geom_bar() +
  labs(title="Government Ownership of Housing Brooklyn", x="Permit Year", y="Cnt") +
  facet_wrap(~Job_Type, ncol=2, scales = 'free')

bklyn_individ_housing <- bklyn_housing[bklyn_housing$`Ownership Reduced` == "Private For-Profit",]
ggplot(data=bklyn_individ_housing, aes(x=PermitYear, fill=`Ownership`)) +
  geom_bar(position='fill') +
  labs(title="Individual Ownership of Housing Brooklyn", x="Permit Year", y="Cnt") +
  facet_wrap(~Job_Type, ncol=2, scales = 'free')


bronx_gov_housing <- bronx_housing[bronx_housing$`Ownership Reduced` == "Government, City",]
ggplot(data=bronx_gov_housing, aes(x=PermitYear, fill=`Ownership`)) +
  geom_bar() +
  labs(title="Government Ownership of Housing Bronx", x="Permit Year", y="Cnt") +
  facet_wrap(~Job_Type, ncol=2, scales = 'free')

manhattan_gov_housing <- manhattan_housing[manhattan_housing$`Ownership Reduced` == "Government, City",]
ggplot(data=manhattan_gov_housing, aes(x=PermitYear, fill=`Ownership`)) +
  geom_bar() +
  labs(title="Government Ownership of Housing Manhattan", x="Permit Year", y="Cnt") +
  facet_wrap(~Job_Type, ncol=2, scales = 'free')

queens_gov_housing <- queens_housing[queens_housing$`Ownership Reduced` == "Government, City",]
ggplot(data=queens_gov_housing, aes(x=PermitYear, fill=`Ownership`)) +
  geom_bar() +
  labs(title="Government Ownership of Housing Queens", x="Permit Year", y="Count") +
  facet_wrap(~Job_Type, ncol=2, scales = 'free')
```

```{r}
library(leaflet)
housing_new = housing[housing$Job_Type=="New Building",]
qpal <- colorNumeric("YlGn",domain=housing_new$PermitYear)


map <- leaflet () %>% 
  addProviderTiles(
    "OpenStreetMap",
    # give the layer a name
    group = "OpenStreetMap"
  ) %>%
  addCircleMarkers(data=housing_new, lat=~Latitude, lng=~Longitude, color = ~qpal(housing_new$PermitYear), radius=.01, group="circles")
  
map
```

```{r}
housing_alter = housing[housing$Job_Type=="Alteration",]

map <- leaflet () %>% 
  addProviderTiles(
    "OpenStreetMap",
    # give the layer a name
    group = "OpenStreetMap"
  ) %>%
  addCircleMarkers(data=housing_alter, lat=~Latitude, lng=~Longitude, color = ~qpal(housing_alter$PermitYear), radius=.01, group="circles")
  
map
```